# Generated by Django 4.0.6 on 2022-09-22 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=2)),
                ('last_name', models.CharField(max_length=2)),
                ('nickname', models.CharField(max_length=10)),
                ('profile_image_url', models.CharField(max_length=2000)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.IntegerField()),
                ('phone_number', models.CharField(max_length=14)),
                ('gender', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
